version: '3'
services:
  calcuco:
    image: calcuco:latest
    environment:
      PORT: 3000
      PROXY_API: http://calcuco-api:8080/
    ports:
      - 3000:3000
  calcuco-api:
    image: calcuco-api:latest
    ports:
      - 8080:8080